### ISSUE TITLE
Loading 2.0 version for 4.2.x instances

### ISSUE THREAD

**Issue by SKLCLU** [Write/TangerineUI-Userscript#1]
For some reason it's now loading the incompatible with 4.2 instances new versions. The colors and icons look off. Had to disable the script.

**Comment by Write** [comment]
Hello,
Thanks for opening an issue.
I'm thinking about a way to "choose" which version is loaded from a "commit id" or tag release instead of always fetching latest pushed version, but that would need to be set manually (ie : if there's an update one would need to change the the tag manually in the script)

**Comment by Write** [comment]
Should be fixed in 2.0.0 (#2)
Should dynamically load the right css based on your instance version.  
Warning though, you should change the tag used in var tag_above_or_equals_4_3_0 when Nileane release a new pre-release.
